# Generated by Django 2.2.2 on 2019-07-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manynotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='category',
            field=models.CharField(choices=[('Kid', 'Dzieci'), ('Mix', 'Mieszany'), ('Women', 'Kobiecy'), ('W', 'Warsztaty'), ('Men', 'Męski')], default=2, max_length=5),
            preserve_default=False,
        ),
    ]
