# Generated by Django 2.2.2 on 2019-07-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manynotes', '0002_notes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.CharField(choices=[('Kid', 'Dzieci'), ('Mix', 'Mieszany'), ('Women', 'Kobiecy'), ('W', 'Warsztaty'), ('Men', 'Męski')], default='W', max_length=5),
        ),
    ]
